version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 3
  reviewers:
  - milmazz
  assignees:
  - milmazz
  ignore:
  - dependency-name: ex_doc
    versions: '>= 0.24'
  - dependency-name: credo
    versions: '>= 1.6'
  - dependency-name: dialyxir
    versions: '>= 1.0'
